name: Pipelines

on:
  push:
    branches:
      - develop
      - master
      - feature/**
      - release/**

defaults:
  run:
    shell: pwsh

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup Docker
        uses: crazy-max/ghaction-setup-docker@v3.5.0

      - name: Build
        run: |
          dotnet build ./AspNetApp.Api.sln -c Release --nologo
          dotnet test ./AspNetApp.Api.sln -c Release --no-restore --no-build --nologo --verbosity normal
          dotnet publish ./src/AspNetApp.Api/AspNetApp.Api.csproj -c Release -o ./artifacts --no-restore --no-build --nologo
