// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © RichillCapital
import RichillCapital/Charts/2 as charts
import RichillCapital/Domain/10 as core
import RichillCapital/Resources/1 as api

//@version=6
strategy(
  title = 'TV-BINANCE:BTCUSDT.P-M15L-001', 
  shorttitle = 'TV-BINANCE:BTCUSDT.P-M15L-001',
  overlay = true,
  initial_capital = 300000,
  default_qty_value = 30000,
  default_qty_type = strategy.cash,
  commission_value = 0.04,
  commission_type = strategy.commission.percent)

int channelLength = 220
int startTime = timestamp(year, month, dayofmonth(time), 15, 0, 0)
int endTime = timestamp(year, month, dayofmonth(time), 22, 0, 0)

int atrLength = 20
float stopLossAtrMultiplier = 3
float profitTargetAtrMultiplier = 7.5

series float upperBand = ta.highest((high[1] * 2 + close[1]) / 3, channelLength)
series float lowerBand = ta.lowest((low[1] * 2 + close[1]) / 3, channelLength) 
series float atrValue = ta.atr(atrLength)

var float stopLossPrice = na
var float profitTargetPrice = na  
var float maxProfitPoints = na

bool crossOverUpperBand = ta.crossover(close, upperBand)
bool crossUnderLowerBand = ta.crossunder(close, lowerBand)
bool inTimeRange = time >= startTime and time <= endTime
bool crossUnderStopLoss = ta.crossunder(close, stopLossPrice)
bool crossUnderTrailingStop = ta.crossunder(close, strategy.position_avg_price + maxProfitPoints * 0.8)

api.CreateSignalRequest req = api.CreateSignalRequest.new(signalSourceId = 'TV-BINANCE:BTCUSDT.P-M15L-001')

if strategy.position_size == 0 
    stopLossPrice := 0  
    profitTargetPrice := 0  
    maxProfitPoints := 0  

    if crossOverUpperBand and inTimeRange
        orderQuantity = math.round(strategy.default_entry_qty(close), 3)
        req.tradeType := core.TradeType.Buy
        req.quantity := orderQuantity
        
        stopLossPrice := close - atrValue * stopLossAtrMultiplier
        profitTargetPrice := close + atrValue * profitTargetAtrMultiplier
        
        strategy.entry('Enter long', direction = strategy.long, qty = orderQuantity)
        api.createSignal(req)

if strategy.position_size != 0 
    if high > strategy.position_avg_price + maxProfitPoints
        maxProfitPoints := high - strategy.position_avg_price

    if crossUnderLowerBand
        req.tradeType := core.TradeType.Sell
        req.quantity := math.abs(strategy.position_size)
        strategy.close_all(comment = 'Exit long')
        api.createSignal(req)

    if crossUnderStopLoss
        req.tradeType := core.TradeType.Sell
        req.quantity := math.abs(strategy.position_size)
        strategy.close_all(comment = 'Stop loss')
        api.createSignal(req)

    if strategy.position_avg_price + maxProfitPoints >= profitTargetPrice and crossUnderTrailingStop
        req.tradeType := core.TradeType.Sell
        req.quantity := math.abs(strategy.position_size)
        strategy.close_all(comment = 'Trailing stop')
        api.createSignal(req)

charts.clearLabels()
charts.showPositionInfo()
