name: ASP.NET API Template Workflow

on:
  push:
    branches:
      - feature/api/aspnet
      - develop

defaults:
  run:
    shell: pwsh

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x