name: Asp.Net Api Template CI

on:
  push:
    branches:
      - feature/api/aspnet

env:
  DOTNET_VERSION: 8.0.x
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install template
        run: dotnet new install ./templates/Api/AspNet

      - name: Build and test ASP.NET api template
        run: |
          mkdir TestAspNetApp
          Push-Location TestAspNetApp

          dotnet new api-aspnet -n TestAspNetApp -o .
          
          dotnet build ./TestAspNetApp.Api.sln -c ${{ env.BUILD_CONFIGURATION }} 
          dotnet test ./TestAspNetApp.Api.sln -c ${{ env.BUILD_CONFIGURATION }} 
          dotnet publish ./src/TestAspNetApp.Api/TestAspNetApp.Api.csproj -c ${{ env.BUILD_CONFIGURATION }} -o ./artifacts

          Pop-Location
          Remove-Item -Recurse -Force TestAspNetApp

    