name: Continue Deployment

on:
  workflow_run:
    workflows:
      - Continue Integration
    types:
      - completed

defaults:
  run:
    shell: pwsh

jobs:
  develop-artifacts:
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'success' && github.ref_name == 'develop' 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Setup
        run: |
          Write-Host "Released debug!"

  release-artifacts:
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'success' && startsWith(github.ref_name, 'release/') 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Setup
        run: |
          Write-Host "Released!"

  production:
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'success' && github.ref_name == 'master' 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Setup
        run: |
          Write-Host "Produciotn ready!"