name: Continue Integration

on:
  workflow_run:
    workflows:
      - Continue Integration
    types:
      - completed

defaults:
  run:
    shell: pwsh
      
jobs:
  develop-artifacts:
    runs-on: windows-latest
    
    if: github.ref_name == 'develop' && github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  release-artifacts:
    runs-on: windows-latest

    if: startsWith(github.ref_name, 'release/') && github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  push-to-nuget:
     runs-on: windows-latest

     if: github.ref_name == 'master' && github.event.workflow_run.conclusion == 'success'

     steps:
       - name: Checkout repository
         uses: actions/checkout@v4