name: Continue Integration

on:
  push:
    branches:
      - develop
      - feature/**
      - release/**

defaults:
  run:
    shell: pwsh

jobs:
  api-aspnet-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup Docker
        uses: crazy-max/ghaction-setup-docker@v3.5.0
                
      - name: Test ASP.NET Core API Template
        run: ./build/ApiAspNet.Template.Tests.ps1

  web-nuxt-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Test Nuxt.js Web Template
        run: |
            npm install -g pnpm
            ./build/NuxtWeb.Template.Tests.ps1

  release:
    runs-on: windows-latest

    needs: [api-aspnet-test, web-nuxt-test]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2
        with:
          nuget-version: 5.x

      - name: Pack NuGet packages
        run: nuget pack .\RichillCapital.Templates.nuspec -NoDefaultExclude -OutputDirectory ./artifacts -Properties Configuration=Release
      
      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RichillCapital.Templates-0.0.0
          path: ./artifacts