name: Continue Integration

on:
  push:
    branches:
      - feature/**/*

defaults:
  run:
    shell: pwsh

env: 
  DOTNET_VERSION: 8.0.x

jobs:
  api-aspnet-test:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Install template
        run: dotnet new install ./templates/Api/AspNet

      - name: Test
        run: |
          mkdir ./TestAspNetApp
          Push-Location ./TestAspNetApp
          
          Write-Host "Creating new project"
          dotnet new api-aspnet -n TestAspNetApp -o ./

          dotnet build ./TestAspNetApp.Api.sln -c Release
          dotnet test ./TestAspNetApp.Api.sln -c Release
          dotnet publish ./src/TestAspNetApp.Api/TestAspNetApp.Api.csproj -c Release -o ./artifacts

          Pop-Location
          Remove-Item ./TestAspNetApp -Recurse -Force


          