name: Continue Integration

on:
  push:
    branches:
      - develop
      - feature/**/*

defaults:
  run:
    shell: pwsh

jobs:
  web-nuxt-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Test Nuxt.js Web Template
        run: |
            npm install -g pnpm
            ./build/NuxtWeb.Template.Tests.ps1