name: Push to NuGet

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

defaults:
  run:
    shell: pwsh

jobs:
  push-to-nuget:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NuGet CLI
        uses: NuGet/setup-nuget@v1
        with:
          nuget-version: 'latest'

      - name: Pack templates
        run: nuget pack ./RichillCapital.Templates.nuspec -Version 0.0.2 -Prop Configuration=Release -OutputDirectory ./artifacts -NoDefaultExcludes

      - name: Push to NuGet Gallery
        run: nuget push ./artifacts/RichillCapital.Templates.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate