name: TradingView Signal Source Template CI

on:
  push:
    branches:
      - feature/source/tv

defaults:
  run:
    shell: pwsh

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: Install template
        run: dotnet new install ./templates/SignalSource/TradingView

      - name: Test
        run: |
          mkdir TestTradingViewStrategy 
          Push-Location .\TestTradingViewStrategy
            
          dotnet new source-tv -n TestTradingViewStrategy -o .
          
          Pop-Location
          Remove-Item -Recurse -Force .\TestTradingViewStrategy
          
