name: TradingView Signal Source Template CI

on:
  push:
    branches:
      - feature/source/aspnet

defaults:
  run:
    shell: pwsh

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: Setup NuGet CLI
        uses: NuGet/setup-nuget@v1
        with:
          nuget-version: 5.x

      - name: Install template
        run: dotnet new install ./templates/Api/AspNet

      - name: Test
        run: |
          mkdir TestAspNetApp 
          Push-Location .\TestAspNetApp

          dotnet new api-aspnet -n TestAspNetApp -o .
          dotnet build .\TestAspNetApp.Api.sln -c Release
          dotnet test .\TestAspNetApp.Api.sln -c Release
          dotnet publish .\src\TestAspNetApp.Api\TestAspNetApp.Api.csproj -c Release -o .\artifacts
          
          docker build -t .
          
          Pop-Location
          Remove-Item -Recurse -Force .\TestAspNetApp
          
